name: composer update

on:
  schedule:
    - cron: '0 4 * * 5' #UTC

jobs:
  composer:
    uses: kawax/composer-workflow/.github/workflows/update.yml@v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      extensions: mbstring
      git-name: kawax
      git-email: 1502086+kawax@users.noreply.github.com
